 Resolving package versions...
 Installed VersionParsing ───── v1.1.3
 Installed Conda ────────────── v1.3.0
 Installed Parsers ──────────── v0.3.10
 Installed OrderedCollections ─ v1.1.0
 Installed PyCall ───────────── v1.91.2
 Installed MacroTools ───────── v0.5.2
 Installed DataStructures ───── v0.17.6
 Installed JSON ─────────────── v0.21.0
 Installed Compat ───────────── v2.2.0
  Updating `~/.julia/environments/v1.0/Project.toml`
  [438e738f] + PyCall v1.91.2
  Updating `~/.julia/environments/v1.0/Manifest.toml`
  [34da2185] + Compat v2.2.0
  [8f4d0f93] + Conda v1.3.0
  [864edb3b] + DataStructures v0.17.6
  [682c06a0] + JSON v0.21.0
  [1914dd2f] + MacroTools v0.5.2
  [bac558e1] + OrderedCollections v1.1.0
  [69de0a69] + Parsers v0.3.10
  [438e738f] + PyCall v1.91.2
  [81def892] + VersionParsing v1.1.3
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 
  Building Conda ─→ `~/.julia/packages/Conda/kLXeC/deps/build.log`
  Building PyCall → `~/.julia/packages/PyCall/ttONZ/deps/build.log`
   Testing PyCall
 Resolving package versions...
    Status `/tmp/tmptQGn6Q/Manifest.toml`
  [34da2185] Compat v2.2.0
  [8f4d0f93] Conda v1.3.0
  [864edb3b] DataStructures v0.17.6
  [682c06a0] JSON v0.21.0
  [1914dd2f] MacroTools v0.5.2
  [bac558e1] OrderedCollections v1.1.0
  [69de0a69] Parsers v0.3.10
  [438e738f] PyCall v1.91.2
  [81def892] VersionParsing v1.1.3
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
┌ Info: Python version 3.6.8 from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0, PYTHONHOME=/usr:/usr
│ ENV[PYTHONPATH]=
│ ENV[PYTHONHOME]=
└ ENV[PYTHONEXECUTABLE]=
Test Summary: | Pass  Total
conversions   |  431    431
Test Summary: | Pass  Total
pydef         |    8      8
Test Summary: | Pass  Total
callback      |    3      3
Test Summary: | Pass  Total
throwing show |    4      4
Test Summary: | Pass  Total
PyIterator    |   14     14
Test Summary: | Pass  Total
atexit        |    1      1
Test Summary: | Pass  Total
pycall!       |   16     16
Warning: skipping array related buffer tests since NumPy not available
Test Summary: | Pass  Total
PyBuffer      |    5      5
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 15-23: surrogates not allowed
Using base prefix '/usr'
New python executable in /tmp/tmpYcEkKx/ϵνιℓ/bin/python3.6
Also creating executable in /tmp/tmpYcEkKx/ϵνιℓ/bin/python
ERROR: The executable /tmp/tmpYcEkKx/ϵνιℓ/bin/python3.6 is not functioning
ERROR: It thinks sys.prefix is '/root/.julia/packages/PyCall/ttONZ/test' (should be '/tmp/tmpYcEkKx/\udccf\udcb5\udcce\udcbd\udcce\udcb9\udce2\udc84\udc93')
ERROR: virtualenv is not compatible with this system or executable
Running virtualenv with interpreter /usr/bin/python3.6
virtualenv activation: Error During Test at /root/.julia/packages/PyCall/ttONZ/test/test_venv.jl:53
  Got exception outside of a @test
  failed process: Process(`virtualenv --python=python3.6 /tmp/tmpYcEkKx/ϵνιℓ`, ProcessExited(100)) [100]
  Stacktrace:
   [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
   [2] pipeline_error at ./process.jl:705 [inlined]
   [3] #run#505(::Bool, ::Function, ::Cmd) at ./process.jl:663
   [4] run at ./process.jl:661 [inlined]
   [5] (::getfield(Main, Symbol("##43#44")){String})(::String) at /root/.julia/packages/PyCall/ttONZ/test/test_venv.jl:66
   [6] mktempdir(::getfield(Main, Symbol("##43#44")){String}, ::String) at ./file.jl:581
   [7] mktempdir(::Function) at ./file.jl:579
   [8] macro expansion at /root/.julia/packages/PyCall/ttONZ/test/test_venv.jl:60 [inlined]
   [9] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [10] top-level scope at /root/.julia/packages/PyCall/ttONZ/test/test_venv.jl:54
   [11] include at ./boot.jl:317 [inlined]
   [12] include_relative(::Module, ::String) at ./loading.jl:1044
   [13] include(::Module, ::String) at ./sysimg.jl:29
   [14] include(::String) at ./client.jl:392
   [15] top-level scope at none:0
   [16] include at ./boot.jl:317 [inlined]
   [17] include_relative(::Module, ::String) at ./loading.jl:1044
   [18] include(::Module, ::String) at ./sysimg.jl:29
   [19] include(::String) at ./client.jl:392
   [20] top-level scope at none:0
   [21] eval(::Module, ::Any) at ./boot.jl:319
   [22] exec_options(::Base.JLOptions) at ./client.jl:243
   [23] _start() at ./client.jl:425
Test Summary:         | Error  Total
virtualenv activation |     1      1
ERROR: LoadError: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /root/.julia/packages/PyCall/ttONZ/test/test_venv.jl:53
in expression starting at /root/.julia/packages/PyCall/ttONZ/test/runtests.jl:788
ERROR: Package PyCall errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:120
 [2] #test#65(::Bool, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1357
 [3] #test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:0 [inlined]
 [4] #test#44(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:278
 [5] test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:263 [inlined]
 [6] #test#43 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:260 [inlined]
 [7] test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:260 [inlined]
 [8] #test#42 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:259 [inlined]
 [9] test at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:259 [inlined]
 [10] #test#41 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:258 [inlined]
 [11] test(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:258
 [12] top-level scope at none:0
